!!python/object/apply:collections.OrderedDict
- - - ent_coef
    - 1.5666550584860516e-06
  - - env_wrapper
    - - rl_zoo3.wrappers.FrameSkip:
          skip: 2
      - gymnasium.wrappers.resize_observation.ResizeObservation:
          shape: 64
      - gymnasium.wrappers.gray_scale_observation.GrayScaleObservation:
          keep_dim: true
  - - frame_stack
    - 4
  - - gae_lambda
    - 0.9549244758833236
  - - gamma
    - 0.9942776405534832
  - - learning_rate
    - 1.8971962220405576e-05
  - - max_grad_norm
    - 2.2574480552177127
  - - n_envs
    - 4
  - - n_steps
    - 64
  - - n_timesteps
    - 200000
  - - normalize
    - '{''norm_obs'': False, ''norm_reward'': True}'
  - - normalize_advantage
    - false
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-4.84, ortho_init=True, activation_fn=nn.Tanh, net_arch=dict(pi=[256],
      vf=[256]), )
  - - sde_sample_freq
    - 16
  - - use_rms_prop
    - false
  - - use_sde
    - true
  - - vf_coef
    - 0.15164696385898477
