!!python/object/apply:collections.OrderedDict
- - - ent_coef
    - 0.0
  - - gae_lambda
    - 1.0
  - - gamma
    - 0.99
  - - learning_rate
    - 0.0007
  - - n_envs
    - 4
  - - n_steps
    - 100
  - - n_timesteps
    - 200000
  - - normalize
    - true
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=0.0, ortho_init=False)
  - - sde_sample_freq
    - 16
  - - use_sde
    - true
  - - vf_coef
    - 0.5
