!!python/object/apply:collections.OrderedDict
- - - algo
    - td3
  - - conf_file
    - null
  - - device
    - auto
  - - env
    - HalfCheetah-v4
  - - env_kwargs
    - null
  - - eval_env_kwargs
    - null
  - - eval_episodes
    - 5
  - - eval_freq
    - 10000
  - - gym_packages
    - []
  - - hyperparams
    - batch_size: 256
      buffer_size: 1000000
      gamma: 0.99
      learning_rate: 0.001
      learning_starts: 10000
      n_timesteps: 800000
      policy: MlpPolicy
      tau: 0.005
  - - log_folder
    - C:\Users\david\Documents\TFM\Enviroments\HalfCheetah\td3\custom_training\2024-07-07_13-25-54
  - - log_interval
    - -1
  - - max_total_trials
    - null
  - - n_eval_envs
    - 2
  - - n_evaluations
    - null
  - - n_jobs
    - 1
  - - n_startup_trials
    - 10
  - - n_timesteps
    - 800000
  - - n_trials
    - 500
  - - no_optim_plots
    - false
  - - num_threads
    - -1
  - - optimization_log_path
    - null
  - - optimize_hyperparameters
    - false
  - - progress
    - false
  - - pruner
    - median
  - - sampler
    - tpe
  - - save_freq
    - -1
  - - save_replay_buffer
    - false
  - - seed
    - 4068593324
  - - storage
    - null
  - - study_name
    - null
  - - tensorboard_log
    - ''
  - - track
    - false
  - - trained_agent
    - ''
  - - truncate_last_trajectory
    - true
  - - uuid
    - false
  - - vec_env
    - dummy
  - - verbose
    - 1
  - - wandb_entity
    - null
  - - wandb_project_name
    - sb3
  - - wandb_tags
    - []
