!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - buffer_size
    - 1000000
  - - gamma
    - 0.99
  - - learning_rate
    - 0.001
  - - learning_starts
    - 10000
  - - n_timesteps
    - 800000
  - - noise_std
    - 0.1
  - - noise_type
    - normal
  - - policy
    - MlpPolicy
  - - tau
    - 0.005
