!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - buffer_size
    - 1000000
  - - gamma
    - 0.99
  - - learning_rate
    - 0.001
  - - learning_starts
    - 100
  - - n_timesteps
    - 450000
  - - noise_std
    - 0.5
  - - noise_type
    - ornstein-uhlenbeck
  - - policy
    - MlpPolicy
  - - tau
    - 0.005
